// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgdb

import (
	"time"
)

type PasswordToken struct {
	ID        int64
	Token     string
	UserID    int64
	CreatedAt time.Time
}

type User struct {
	ID        int64
	Name      string
	Email     string
	Password  string
	Verified  bool
	Admin     bool
	CreatedAt time.Time
}
