// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_tokens.sql

package pgdb

import (
	"context"
	"time"
)

const createPasswordToken = `-- name: CreatePasswordToken :one
INSERT INTO password_tokens (token, user_id)
VALUES ($1::text, $2::bigint)
RETURNING id, token, user_id, created_at
`

type CreatePasswordTokenParams struct {
	Token  string
	UserID int64
}

func (q *Queries) CreatePasswordToken(ctx context.Context, arg CreatePasswordTokenParams) (PasswordToken, error) {
	row := q.db.QueryRow(ctx, createPasswordToken, arg.Token, arg.UserID)
	var i PasswordToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deletePasswordTokensByUser = `-- name: DeletePasswordTokensByUser :exec
DELETE FROM password_tokens
WHERE user_id = $1
`

func (q *Queries) DeletePasswordTokensByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deletePasswordTokensByUser, userID)
	return err
}

const getPasswordToken = `-- name: GetPasswordToken :one
SELECT id, token, user_id, created_at FROM password_tokens
WHERE id = $1::bigint
  AND user_id = $2::bigint
  AND created_at >= $3::timestamptz
`

type GetPasswordTokenParams struct {
	ID           int64
	UserID       int64
	CreatedAfter time.Time
}

func (q *Queries) GetPasswordToken(ctx context.Context, arg GetPasswordTokenParams) (PasswordToken, error) {
	row := q.db.QueryRow(ctx, getPasswordToken, arg.ID, arg.UserID, arg.CreatedAfter)
	var i PasswordToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}
