// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgdb

import (
	"context"
)

type Querier interface {
	CreatePasswordToken(ctx context.Context, arg CreatePasswordTokenParams) (PasswordToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePasswordTokensByUser(ctx context.Context, userID int64) error
	GetPasswordToken(ctx context.Context, arg GetPasswordTokenParams) (PasswordToken, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	SetUserVerified(ctx context.Context, id int64) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
}

var _ Querier = (*Queries)(nil)
