// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgdb

import (
	"context"
)

type Querier interface {
	CountPasswordTokensByUser(ctx context.Context, userID int64) (int64, error)
	CreatePasswordToken(ctx context.Context, arg CreatePasswordTokenParams) (PasswordToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePasswordTokensByUser(ctx context.Context, userID int64) error
	GetPasswordToken(ctx context.Context, arg GetPasswordTokenParams) (PasswordToken, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	SetUserAdmin(ctx context.Context, arg SetUserAdminParams) (User, error)
	SetUserVerified(ctx context.Context, id int64) (User, error)
	UpdatePasswordTokenCreatedAt(ctx context.Context, arg UpdatePasswordTokenCreatedAtParams) (int64, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
}

var _ Querier = (*Queries)(nil)
