// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package pgdb

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password, verified, admin)
VALUES (
    $1::text,
    LOWER($2::text),
    $3::text,
    $4::boolean,
    $5::boolean
)
RETURNING id, name, email, password, verified, admin, created_at
`

type CreateUserParams struct {
	Name     string
	Email    string
	Password string
	Verified bool
	Admin    bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Verified,
		arg.Admin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Verified,
		&i.Admin,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, password, verified, admin, created_at FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Verified,
		&i.Admin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password, verified, admin, created_at FROM users
WHERE email = LOWER($1::text)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Verified,
		&i.Admin,
		&i.CreatedAt,
	)
	return i, err
}

const setUserAdmin = `-- name: SetUserAdmin :one
UPDATE users
SET admin = $1::boolean
WHERE id = $2::bigint
RETURNING id, name, email, password, verified, admin, created_at
`

type SetUserAdminParams struct {
	Admin bool
	ID    int64
}

func (q *Queries) SetUserAdmin(ctx context.Context, arg SetUserAdminParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserAdmin, arg.Admin, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Verified,
		&i.Admin,
		&i.CreatedAt,
	)
	return i, err
}

const setUserVerified = `-- name: SetUserVerified :one
UPDATE users
SET verified = TRUE
WHERE id = $1
RETURNING id, name, email, password, verified, admin, created_at
`

func (q *Queries) SetUserVerified(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, setUserVerified, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Verified,
		&i.Admin,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password = $1::text
WHERE id = $2::bigint
RETURNING id, name, email, password, verified, admin, created_at
`

type UpdateUserPasswordParams struct {
	Password string
	ID       int64
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.Password, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Verified,
		&i.Admin,
		&i.CreatedAt,
	)
	return i, err
}
